tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/bundle"
tap "homebrew/services"
tap "sanemat/font"
tap "caskroom/versions"
tap "caskroom/cask"
brew "cask"
brew "docker"
brew "ghq"
brew "git"
brew "hub"
brew "hugo"
brew "imagemagick", link: false
brew "imagemagick@6", link: true
brew "jq"
brew "mysql"
brew "neovim"
brew "node"
brew "node-build", args: ["HEAD"]
brew "pandoc"
brew "reattach-to-user-namespace"
brew "rpm2cpio"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "homebrew/php/composer"
brew "homebrew/php/wp-cli"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "brackets"
cask "dash"
cask "google-backup-and-sync"
cask "google-drive-file-stream"
cask "keycast"
cask "mactex"
cask "virtualbox"
cask "caskroom/versions/discord-canary"
cask "caskroom/versions/google-chrome-canary"
